-- 058: Trigger keeps locations.branch_id denormalized.
-- For BRANCH rows, branch_id = id (self-reference).
-- For any other type, branch_id is copied from the parent location.
-- Fires BEFORE INSERT or BEFORE UPDATE of parent_id/type.

CREATE OR REPLACE FUNCTION fn_locations_set_branch_id() RETURNS TRIGGER AS $$
DECLARE
    v_branch UUID;
BEGIN
    IF NEW.type = 'BRANCH' THEN
        -- Branch self-references; id is generated by DEFAULT, but on UPDATE it already exists.
        NEW.branch_id := COALESCE(NEW.id, NEW.branch_id);
        -- Note: on INSERT the id is filled by uuid_generate_v4() DEFAULT before
        -- BEFORE INSERT triggers run, so NEW.id is non-null here.
        IF NEW.branch_id IS NULL THEN
            NEW.branch_id := NEW.id;
        END IF;
        RETURN NEW;
    END IF;

    IF NEW.parent_id IS NULL THEN
        RAISE EXCEPTION 'Non-branch locations must have parent_id';
    END IF;

    SELECT branch_id INTO v_branch FROM locations WHERE id = NEW.parent_id;
    IF v_branch IS NULL THEN
        RAISE EXCEPTION 'Parent location % has no branch_id', NEW.parent_id;
    END IF;
    NEW.branch_id := v_branch;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_locations_set_branch_id ON locations;
CREATE TRIGGER trg_locations_set_branch_id
BEFORE INSERT OR UPDATE OF parent_id, type ON locations
FOR EACH ROW EXECUTE FUNCTION fn_locations_set_branch_id();
