-- Migration 078: Replenishment settings & procurement draft staging
-- Feature: A-12 Suggested-PO / Replenishment
-- 
-- Adds two tables:
-- 1. replenishment_settings — per-product overrides for the dynamic reorder formula
-- 2. replenishment_drafts  — staged draft POs awaiting human-in-the-loop approval

-- Per-product replenishment overrides (optional; falls back to global defaults).
-- When a row exists for a product, the recommendation engine uses these values
-- instead of the system-wide RecommendationConfig defaults.
CREATE TABLE IF NOT EXISTS replenishment_settings (
    id                      UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    product_id              UUID NOT NULL REFERENCES products(id) ON DELETE CASCADE,
    min_safety_stock        DECIMAL(19,4) NOT NULL DEFAULT 0,
    velocity_window_days    INT NOT NULL DEFAULT 90,
    lead_time_override_days DECIMAL(10,2),  -- NULL = use vendor average_lead_time_days
    created_at              TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at              TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (product_id)
);

-- Staged draft POs awaiting human approval via the Procurement Dashboard.
-- Each row wraps an existing purchase_orders row (status=DRAFT) with additional
-- review metadata. The procurement manager reviews, edits, and approves/rejects
-- through the dashboard UI.
CREATE TABLE IF NOT EXISTS replenishment_drafts (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    po_id           UUID NOT NULL REFERENCES purchase_orders(id) ON DELETE CASCADE,
    vendor_id       UUID NOT NULL REFERENCES vendors(id),
    status          TEXT NOT NULL DEFAULT 'PENDING_REVIEW'
                    CHECK (status IN ('PENDING_REVIEW','APPROVED','REJECTED','EXPIRED')),
    generated_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    reviewed_by     UUID REFERENCES accounts(id),
    reviewed_at     TIMESTAMPTZ,
    notes           TEXT,
    confidence      DECIMAL(5,2) NOT NULL DEFAULT 0,     -- 0–100 confidence score
    total_lines     INT NOT NULL DEFAULT 0,
    total_est_cost  DECIMAL(19,4) NOT NULL DEFAULT 0,
    UNIQUE (po_id)
);

CREATE INDEX idx_replenishment_drafts_status ON replenishment_drafts(status);
CREATE INDEX idx_replenishment_drafts_vendor ON replenishment_drafts(vendor_id);

-- Add SUGGESTED source to purchase_orders source CHECK constraint.
-- The existing constraint from 055_po_source.sql allows: MANUAL, REORDER, SPECIAL_ORDER, A2A.
-- We add SUGGESTED for draft POs generated by the replenishment engine.
ALTER TABLE purchase_orders DROP CONSTRAINT IF EXISTS purchase_orders_source_check;
ALTER TABLE purchase_orders ADD CONSTRAINT purchase_orders_source_check
    CHECK (source IN ('MANUAL', 'REORDER', 'SPECIAL_ORDER', 'A2A', 'SUGGESTED'));
